// Generated by scripts/build-populations.mjs. Rough scenarios, not census counts.
export const POPULATIONS={
 "labrador-retriever": {
  "estimate": 19000000,
  "low": 7200000,
  "high": 48000000,
  "year": 2026,
  "method": "international",
  "lifespan": 12,
  "annualRegistrations": 200061
 },
 "golden-retriever": {
  "estimate": 9900000,
  "low": 3700000,
  "high": 25000000,
  "year": 2026,
  "method": "international",
  "lifespan": 11,
  "annualRegistrations": 112028
 },
 "german-shepherd-dog": {
  "estimate": 9900000,
  "low": 3700000,
  "high": 25000000,
  "year": 2026,
  "method": "international",
  "lifespan": 11,
  "annualRegistrations": 112228
 },
 "great-dane": {
  "estimate": 1200000,
  "low": 430000,
  "high": 2900000,
  "year": 2026,
  "method": "international",
  "lifespan": 8.5,
  "annualRegistrations": 16925
 },
 "bernese-mountain-dog": {
  "estimate": 1400000,
  "low": 520000,
  "high": 3400000,
  "year": 2026,
  "method": "international",
  "lifespan": 8.5,
  "annualRegistrations": 20248
 },
 "standard-poodle": {
  "estimate": 3300000,
  "low": 610000,
  "high": 16000000,
  "year": 2026,
  "method": "group-share",
  "lifespan": 14,
  "annualRegistrations": 29239,
  "groupShare": 0.2282
 },
 "border-collie": {
  "estimate": 2200000,
  "low": 830000,
  "high": 5600000,
  "year": 2026,
  "method": "international",
  "lifespan": 13.5,
  "annualRegistrations": 20564
 },
 "australian-shepherd": {
  "estimate": 920000,
  "low": 170000,
  "high": 4600000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13.5,
  "annualRegistrations": 8554
 },
 "beagle": {
  "estimate": 4400000,
  "low": 1700000,
  "high": 11000000,
  "year": 2026,
  "method": "international",
  "lifespan": 12.5,
  "annualRegistrations": 44315
 },
 "english-cocker-spaniel": {
  "estimate": 4600000,
  "low": 1700000,
  "high": 11000000,
  "year": 2026,
  "method": "international",
  "lifespan": 13,
  "annualRegistrations": 44181
 },
 "shiba-inu": {
  "estimate": 1800000,
  "low": 330000,
  "high": 8900000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 14.5,
  "annualRegistrations": 15280
 },
 "siberian-husky": {
  "estimate": 1900000,
  "low": 350000,
  "high": 9400000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13,
  "annualRegistrations": 17985
 },
 "dachshund": {
  "estimate": 12000000,
  "low": 4500000,
  "high": 30000000,
  "year": 2026,
  "method": "international",
  "lifespan": 14,
  "annualRegistrations": 106713
 },
 "cavalier-king-charles-spaniel": {
  "estimate": 3800000,
  "low": 1400000,
  "high": 9600000,
  "year": 2026,
  "method": "international",
  "lifespan": 13.5,
  "annualRegistrations": 35483
 },
 "miniature-schnauzer": {
  "estimate": 4300000,
  "low": 1600000,
  "high": 11000000,
  "year": 2026,
  "method": "international",
  "lifespan": 13.5,
  "annualRegistrations": 39709
 },
 "pomeranian": {
  "estimate": 4100000,
  "low": 760000,
  "high": 20000000,
  "year": 2026,
  "method": "group-share",
  "lifespan": 14,
  "annualRegistrations": 36161,
  "groupShare": 0.7769
 },
 "pembroke-welsh-corgi": {
  "estimate": 3000000,
  "low": 570000,
  "high": 15000000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 12.5,
  "annualRegistrations": 30368
 },
 "newfoundland": {
  "estimate": 450000,
  "low": 85000,
  "high": 2300000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 9.5,
  "annualRegistrations": 5950
 },
 "doberman-pinscher": {
  "estimate": 1700000,
  "low": 650000,
  "high": 4300000,
  "year": 2026,
  "method": "international",
  "lifespan": 11,
  "annualRegistrations": 19682
 },
 "boxer": {
  "estimate": 4200000,
  "low": 1600000,
  "high": 11000000,
  "year": 2026,
  "method": "international",
  "lifespan": 11,
  "annualRegistrations": 47945
 },
 "rottweiler": {
  "estimate": 2700000,
  "low": 1000000,
  "high": 6700000,
  "year": 2026,
  "method": "international",
  "lifespan": 9.5,
  "annualRegistrations": 35505
 },
 "greyhound": {
  "estimate": 250000,
  "low": 100000,
  "high": 750000,
  "year": 2026,
  "method": "racing-stock"
 },
 "australian-cattle-dog": {
  "estimate": 170000,
  "low": 32000,
  "high": 840000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 14,
  "annualRegistrations": 1503
 },
 "english-springer-spaniel": {
  "estimate": 2700000,
  "low": 1000000,
  "high": 6800000,
  "year": 2026,
  "method": "international",
  "lifespan": 13,
  "annualRegistrations": 26095
 },
 "brittany": {
  "estimate": 2000000,
  "low": 740000,
  "high": 4900000,
  "year": 2026,
  "method": "international",
  "lifespan": 13,
  "annualRegistrations": 18957
 },
 "basenji": {
  "estimate": 190000,
  "low": 36000,
  "high": 970000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13.5,
  "annualRegistrations": 1796
 },
 "whippet": {
  "estimate": 2300000,
  "low": 440000,
  "high": 12000000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13.5,
  "annualRegistrations": 21695
 },
 "havanese": {
  "estimate": 610000,
  "low": 110000,
  "high": 3000000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 15,
  "annualRegistrations": 5068
 },
 "bichon-frise": {
  "estimate": 2900000,
  "low": 540000,
  "high": 14000000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 14.5,
  "annualRegistrations": 24626
 },
 "papillon": {
  "estimate": 1900000,
  "low": 360000,
  "high": 9600000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 15,
  "annualRegistrations": 16052
 },
 "jack-russell-terrier": {
  "estimate": 2500000,
  "low": 470000,
  "high": 13000000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 14.5,
  "annualRegistrations": 21583
 },
 "maltese": {
  "estimate": 2700000,
  "low": 1000000,
  "high": 6600000,
  "year": 2026,
  "method": "international",
  "lifespan": 13.5,
  "annualRegistrations": 24604
 },
 "samoyed": {
  "estimate": 1000000,
  "low": 190000,
  "high": 5100000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13,
  "annualRegistrations": 9762
 },
 "dalmatian": {
  "estimate": 1100000,
  "low": 210000,
  "high": 5500000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 12,
  "annualRegistrations": 11425
 },
 "irish-setter": {
  "estimate": 500000,
  "low": 94000,
  "high": 2500000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13.5,
  "annualRegistrations": 4656
 },
 "weimaraner": {
  "estimate": 1000000,
  "low": 190000,
  "high": 5100000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 11.5,
  "annualRegistrations": 11169
 },
 "rhodesian-ridgeback": {
  "estimate": 180000,
  "low": 34000,
  "high": 910000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 11,
  "annualRegistrations": 2073
 },
 "alaskan-malamute": {
  "estimate": 470000,
  "low": 88000,
  "high": 2400000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 12,
  "annualRegistrations": 4899
 },
 "vizsla": {
  "estimate": 550000,
  "low": 100000,
  "high": 2700000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13,
  "annualRegistrations": 5258
 },
 "portuguese-water-dog": {
  "estimate": 230000,
  "low": 43000,
  "high": 1100000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 12.5,
  "annualRegistrations": 2283
 },
 "shetland-sheepdog": {
  "estimate": 1900000,
  "low": 720000,
  "high": 4800000,
  "year": 2026,
  "method": "international",
  "lifespan": 13,
  "annualRegistrations": 18551
 },
 "west-highland-white-terrier": {
  "estimate": 1900000,
  "low": 720000,
  "high": 4800000,
  "year": 2026,
  "method": "international",
  "lifespan": 14,
  "annualRegistrations": 17128
 },
 "yorkshire-terrier": {
  "estimate": 7600000,
  "low": 2900000,
  "high": 19000000,
  "year": 2026,
  "method": "international",
  "lifespan": 13,
  "annualRegistrations": 73551
 },
 "chihuahua": {
  "estimate": 9700000,
  "low": 3600000,
  "high": 24000000,
  "year": 2026,
  "method": "international",
  "lifespan": 15,
  "annualRegistrations": 80795
 },
 "akita": {
  "estimate": 510000,
  "low": 96000,
  "high": 2600000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 12,
  "annualRegistrations": 5317
 },
 "great-pyrenees": {
  "estimate": 210000,
  "low": 40000,
  "high": 1100000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 11,
  "annualRegistrations": 2426
 },
 "collie": {
  "estimate": 72000,
  "low": 13000,
  "high": 360000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13,
  "annualRegistrations": 690
 },
 "german-shorthaired-pointer": {
  "estimate": 2300000,
  "low": 850000,
  "high": 5700000,
  "year": 2026,
  "method": "international",
  "lifespan": 11,
  "annualRegistrations": 25711
 },
 "english-setter": {
  "estimate": 3100000,
  "low": 1200000,
  "high": 7700000,
  "year": 2026,
  "method": "international",
  "lifespan": 13,
  "annualRegistrations": 29672
 },
 "old-english-sheepdog": {
  "estimate": 350000,
  "low": 66000,
  "high": 1800000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 11,
  "annualRegistrations": 4016
 },
 "american-cocker-spaniel": {
  "estimate": 730000,
  "low": 140000,
  "high": 3700000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 12,
  "annualRegistrations": 7609
 },
 "cairn-terrier": {
  "estimate": 540000,
  "low": 100000,
  "high": 2700000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 14,
  "annualRegistrations": 4799
 },
 "italian-greyhound": {
  "estimate": 2700000,
  "low": 500000,
  "high": 13000000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 14.5,
  "annualRegistrations": 23033
 },
 "miniature-pinscher": {
  "estimate": 1300000,
  "low": 250000,
  "high": 6700000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 14,
  "annualRegistrations": 12050
 },
 "belgian-malinois": {
  "estimate": 410000,
  "low": 76000,
  "high": 2000000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 15,
  "annualRegistrations": 3375
 },
 "chesapeake-bay-retriever": {
  "estimate": 65000,
  "low": 12000,
  "high": 330000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 11.5,
  "annualRegistrations": 709
 },
 "flat-coated-retriever": {
  "estimate": 450000,
  "low": 84000,
  "high": 2200000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 9,
  "annualRegistrations": 6192
 },
 "nova-scotia-duck-tolling-retriever": {
  "estimate": 220000,
  "low": 41000,
  "high": 1100000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13,
  "annualRegistrations": 2099
 },
 "giant-schnauzer": {
  "estimate": 120000,
  "low": 22000,
  "high": 600000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13.5,
  "annualRegistrations": 1105
 },
 "keeshond": {
  "estimate": 600000,
  "low": 110000,
  "high": 3000000,
  "year": 2026,
  "method": "group-share",
  "lifespan": 13.5,
  "annualRegistrations": 5514,
  "groupShare": 0.1185
 },
 "australian-kelpie": {
  "estimate": 700000,
  "low": 130000,
  "high": 3500000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13.5,
  "annualRegistrations": 6442
 },
 "norwegian-elkhound": {
  "estimate": 51000,
  "low": 9600,
  "high": 260000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13.5,
  "annualRegistrations": 472
 },
 "finnish-spitz": {
  "estimate": 8900,
  "low": 1700,
  "high": 45000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 14,
  "annualRegistrations": 80
 },
 "border-terrier": {
  "estimate": 520000,
  "low": 98000,
  "high": 2600000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13.5,
  "annualRegistrations": 4849
 },
 "scottish-terrier": {
  "estimate": 520000,
  "low": 97000,
  "high": 2600000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 12,
  "annualRegistrations": 5403
 },
 "welsh-terrier": {
  "estimate": 240000,
  "low": 44000,
  "high": 1200000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13.5,
  "annualRegistrations": 2180
 },
 "rough-collie": {
  "estimate": 620000,
  "low": 120000,
  "high": 3100000,
  "year": 2026,
  "method": "regional-ratio",
  "lifespan": 13,
  "annualRegistrations": 5997
 },
 "mixed-breed-dogs": {
  "estimate": 680000000,
  "low": 460000000,
  "high": 850000000,
  "year": 2026,
  "method": "world-share",
  "populationGroup": "mixed-village"
 }
};
export const POPULATION_BALANCE={
 "reference": 900000000,
 "low": 700000000,
 "high": 1000000000,
 "mixedShare": 0.75,
 "breeds": 157456900,
 "mixed": 680000000,
 "catalog": 837456900,
 "unlisted": 62543100,
 "withinRange": true,
 "note": "Unlisted is a remainder against the reference scenario, not an independent estimate."
};
export const population=b=>POPULATIONS[typeof b==='string'?b:b.id];
export const populationCount=b=>population(b)?.estimate??0;
export const formatPopulation=n=>new Intl.NumberFormat('en',{notation:'compact',maximumSignificantDigits:2}).format(n);
